In [11]:
import cv2, os
import urllib.request
import numpy

haar_file = 'haarcascade_frontalface_default.xml'
face_cascade = cv2.CascadeClassifier(haar_file)
datasets = 'dataset'
print('Training...')
(images, labels, names, id) = ([], [], {}, 0)

for (subdirs, dirs, files) in os.walk(datasets):
    for subdir in dirs:
        names[id] = subdir
        subjectpath = os.path.join(datasets, subdir)
        for filename in os.listdir(subjectpath):
            path = subjectpath + '/' + filename
            label = id
            images.append(cv2.imread(path, 0))
            labels.append(int(label))
        id +=1

(images, labels) = [numpy.array(lis) for lis in [images, labels]]
print(images, labels)                   
(width, height) = (130, 100)
model = cv2.face.LBPHFaceRecognizer_create()
#model =  cv2.face.FisherFaceRecognizer_create()

model.train(images, labels)

#webcam = cv2.VideoCapture(0)
url='http://192.168.1.5:8080/shot.jpg'    
cnt=0

while True:
    imgPath = urllib.request.urlopen(url)
    imgNp = numpy.array(bytearray(imgPath.read()), dtype=np.uint8)
    img = cv2.imdecode(imgNp, -1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),2)
        face = gray[y:y + h, x:x + w]
        face_resize = cv2.resize(face, (width, height))

        prediction = model.predict(face_resize)
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 3)
        if prediction[1]<800:
            cv2.putText(img,'%s - %.0f' % (names[prediction[0]],prediction[1]),(x-10, y-10), cv2.FONT_HERSHEY_PLAIN,2,(0, 0, 255))
            print (names[prediction[0]])
            cnt=0
        else:
            cnt+=1
            cv2.putText(img,'Unknown',(x-10, y-10), cv2.FONT_HERSHEY_PLAIN,1,(0, 255, 0))
            if(cnt>100):
                print("Unknown Person")
                cv2.imwrite("unknown.jpg",img)
                cnt=0
    cv2.imshow('FaceRecognition', img)
    key = cv2.waitKey(10)
    if key == 27:
        break

#webcam.release()
cv2.destroyAllWindows()

Training...
[array([[214, 214, 211, ..., 230, 229, 228],
       [227, 228, 227, ..., 182, 182, 182],
       [223, 226, 227, ..., 227, 229, 230],
       ...,
       [225, 221, 230, ..., 202, 202, 202],
       [218, 214, 222, ..., 202, 202, 202],
       [210, 206, 214, ..., 202, 202, 202]], dtype=uint8)
 array([[224, 225, 225, ..., 192, 190, 187],
       [218, 218, 217, ..., 215, 214, 213],
       [221, 221, 219, ..., 226, 227, 227],
       ...,
       [196, 196, 196, ..., 197, 196, 196],
       [220, 220, 219, ..., 197, 196, 195],
       [197, 198, 199, ..., 196, 195, 194]], dtype=uint8)
 array([[216, 227, 234, ..., 166, 165, 186],
       [213, 221, 228, ..., 174, 147, 182],
       [220, 225, 233, ..., 154, 167, 200],
       ...,
       [215, 216, 216, ..., 200, 203, 202],
       [223, 223, 223, ..., 194, 198, 197],
       [203, 203, 203, ..., 201, 204, 204]], dtype=uint8)
 array([[221, 219, 223, ..., 171, 170, 170],
       [221, 221, 225, ..., 231, 230, 229],
       [223, 222, 225, ...

<ipython-input-11-338c030f48c1>:22: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  (images, labels) = [numpy.array(lis) for lis in [images, labels]]


Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhoni
Dhon

KeyboardInterrupt: 

In [12]:
cv2.destroyAllWindows()